config/routes.rb
Rails.application.routes.draw do

  post "contact", to: "notifications#contact", as: :contact_us

  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create", as: :login_post
  get "logout", to: "sessions#destroy", as: :logout
  get "register", to: "users#new", as: :register_user

  post "user/reset", to: "password_resets#create", as: :password_reset
  get "user/reset", to: "password_resets#new", as: :new_password_reset
  get "user/activate/:token", to: "password_resets#edit", as: :edit_password_reset

  get "dashboard", to: "dashboards#index", as: :dashboard

  resource :users, path: "user"

  resources :events

  root "static_pages#index"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    def new
        set_body_class "tight-col narrow-col"
        if signed_in?
            signout
            redirect_to new_password_reset_url, notice: "You have been signed out to reset your password."
        end
    end

    def create
        user = User.find_by(email: params[:password_reset][:email].downcase)
        if user
            token = User.hash(User.new_token)
            user.update(token: token)
            Notifications.password_reset(token).deliver
        end
        redirect_to root_url, notice: "Your password reset instructions has been sent to your email."
    end

    def edit
        @user = User.find_by(token: params[:token])
        if @user
            signin(@user)
        end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Update User Password</h1>

<%= form_for(@user, url: users_path) do |f| %>
    <div class="field">
        <%= @user.email %>
    </div>

    <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, autofocus: true, placeholder: "New Password" %>
        <%= f.password_field :password_confirmation, placeholder: "New Password Confirmation" %>
    </div>

    <div class="field">
        <%= f.submit "Update Password" %>
    </div>

<% end %>

app/views/password_resets/new.html.erb
<% provide(:title, "Password Reset") %>


<section class="hero">
    <section class="bg-full" data-image-src="<%= image_path('hero-1.jpg') %>">
        <noscript>
            <%= image_tag image_path('hero-1.jpg') %>
        </noscript>
    </section>
    <div class="user-man-description">
        <h1 class="user-man-title">Reset your password.</h1>
        <%= form_for(:password_reset, url: password_reset_path) do |f| %>
            <div class="field">
                <%= f.label :email %>
                <%= f.text_field :email %>
            </div>
            <div class="field action">
                <%= f.submit "Reset" %>
            </div>
        <% end %>
    </div>
</section>