config/routes.rb
Rails.application.routes.draw do

  post "contact", to: "notifications#contact", as: :contact_us

  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create", as: :login_post
  get "logout", to: "sessions#destroy", as: :logout
  get "register", to: "users#new", as: :register_user

  post "user/reset", to: "password_resets#create", as: :password_reset
  get "user/reset", to: "password_resets#new", as: :new_password_reset
  get "user/activate/:token", to: "password_resets#edit", as: :edit_password_reset

  get "dashboard", to: "dashboards#index", as: :dashboard

  resource :users, path: "user"

  resources :events

  root "static_pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :receipts

  # destroy all events if user is destroyed womp womp
  has_many :events, dependent: :destroy

  has_secure_password

  validates :email, uniqueness: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_token
    self.token = User.hash(User.new_token)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :signed_in_user, except: [:new, :create]
    before_action :set_user
    # before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
        set_body_class "dashboard"
        # @users = User.all
        # render @user.to_json
    end

    # GET /users/1
    # GET /users/1.json
    def show
        set_body_class "dashboard"
    end

    # GET /users/new
    def new
        set_body_class "tight-col"
        @user = User.new
    end

    # GET /users/1/edit
    def edit
        set_body_class "dashboard"
    end

    # POST /users
    # POST /users.json
    def create
        set_body_class "tight-col"
        @user = User.new(user_params)

        respond_to do |format|
            if @user.save
                Notifications.welcome(@user).deliver
                signin(@user)
                format.html { redirect_to dashboard_url, notice: 'Your account was successfully created.' }
                format.json { render :show, status: :created, location: dashboard_url }
            else
                format.html { render :new }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
        set_body_class "dashboard"
        respond_to do |format|
            if @user.update(user_params)
                format.html { redirect_to edit_users_url, notice: 'Your account was successfully updated.' }
                format.json { render :show, status: :ok, location: edit_users_url }
            else
                format.html { render :edit }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        set_body_class "dashboard"
        @user.destroy
        respond_to do |format|
            format.html { redirect_to root_url }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
            # @user = User.find(params[:id])
            @user = current_user
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: users_path) do |f| %>
    
    <h1 class="form-title">
        Your Account
    </h1>

    <% if @user.errors.any? %>
        <div id="error_explanation">
            <!-- <h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2> -->

            <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="col-2">
        <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name %>
        </div>
        <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name %>
        </div>
    </div>

    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </div>

    <div class="col-2">
        <div class="field">
            <%= f.label :password, "Password" %><br>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation, "Confirm Password" %><br>
            <%= f.password_field :password_confirmation %>
        </div>
    </div>

    <div class="field action">
        <% unless f.object.new_record? %>
            <%= f.submit "Update" %>
            <%= link_to "Dashboard", dashboard_url %>
        <% else %>
            <%= f.submit "Register" %>
            <%= link_to "Cancel", root_url %>
        <% end %>
    </div>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Account Settings") %>

<section class="section">
    <div class="section-description">
        <%= render 'form' %>
    </div>
</section>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Register") %>


<section class="hero">
    <section class="bg-full" data-image-src="<%= image_path('hero-1.jpg') %>">
        <noscript>
            <%= image_tag image_path('hero-1.jpg') %>
        </noscript>
    </section>
    <div class="user-man-description">
        <h1 class="user-man-title">Working with us.</h1>
        <div class="col-2">
            <div class="col-block">
                <p>We're excited that you've decided to register with us!  You’ll never again need to make all of the arrangements by yourself, or pay WAY TOO MUCH to other professional event services.  We're going to make it easy for you to find fun, personable event planners in an efficient, and cost-effective manner.<br /><br />  <b>Welcome from the plannr staff!</b> </p>
            </div>
            <div class="col-block col-block-right">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<% @user.attributes.each do |k, v| %>
    <p><strong><%= k %></strong>: <%= v %></p>
<% end %>

<%= link_to 'Edit', edit_users_path %>