config/routes.rb
Rails.application.routes.draw do

  post "contact", to: "notifications#contact", as: :contact_us

  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create", as: :login_post
  get "logout", to: "sessions#destroy", as: :logout
  get "register", to: "users#new", as: :register_user

  post "user/reset", to: "password_resets#create", as: :password_reset
  get "user/reset", to: "password_resets#new", as: :new_password_reset
  get "user/activate/:token", to: "password_resets#edit", as: :edit_password_reset

  get "dashboard", to: "dashboards#index", as: :dashboard

  resource :users, path: "user"

  resources :events

  root "static_pages#index"

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :signed_in_user
  before_action { set_body_class "dashboard" }

  def index
    @events = current_user.events
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<% provide(:title, "Dashboard") %>

<section class="section section-header">
    <div class="section-description">
        <h1 class="section-title alignleft">Dashboard</h1>
        <%= link_to "Create Event", new_event_path, { class: "btn btn-primary btn-accent alignright"} %>
    </div>
</section>

<section class="section">
    <div class="section-description">
        <% if @events.any? %>
            <ul class="list-clean">
                <% @events.each do |event| %>
                    <li class="list-item event-content">
                        <div class="col-2">
                            <div class="col-block col-block-9">
                                <h1 class="list-title"><%= link_to event.title, event_path(event) %></h1>
                            </div>
                            <div class="col-block col-block-3 event-status">
                                <p><span class="label">Status:</span> <span class="label-content"><%= event.status %></span></p>
                            </div>
                        </div>
                        <button class="btn-toggle btn btn-primary" type="button">
                            <span class="show">Show</span><span class="hide">Hide</span> Details
                            <span class="toggle-icon arrow-right"></span>
                        </button>
                        <div class="toggle event-details">
                            <div class="col-2">
                                <div class="col-block">
                                    <h1 class="block-title">Event Details</h1>
                                    <%= form_for(event) do |f| %>

                                        <div class="field">
                                            <%= f.label :title %>
                                            <%= f.text_field :title, placeholder: "e.g. seth's birthday" %>
                                        </div>

                                        <div class="col-2">
                                            <div class="field">
                                                <%= f.label :type_of_event, "Category" %>
                                                <%= f.text_field :type_of_event, placeholder: "e.g. birthday" %>
                                            </div>

                                            <div class="field">
                                                <%= f.label :guest_count, "Number of guests" %>
                                                <%= f.text_field :guest_count, placeholder: "e.g. 12" %>
                                            </div>
                                        </div>

                                        <div class="field">
                                            <%= f.label :date, "Event date" %>
                                            <%= f.date_field :date, placeholder: "e.g. 07/14/2018" %>
                                        </div>

                                        <div class="col-2">
                                            <div class="field">
                                                <%= f.label :min_budget, "Minimum budget" %>
                                                <%= f.text_field :min_budget, placeholder: "e.g. $500" %>
                                            </div>

                                            <div class="field">
                                                <%= f.label :max_budget, "Maximum budget" %>
                                                <%= f.text_field :max_budget, placeholder: "e.g. $10,000" %>
                                            </div>
                                        </div>

                                        <% unless Time.current > event.date %>
                                            <div class="field action">
                                                <%= f.submit "Update", class: "btn" %>
                                            </div>
                                        <% end %>
                                    <% end %>
                                </div>
                                <div class="col-block">
                                    <h1 class="block-titlte">Your Planner</h1>
                                    <p>Coming soon...</p>
                                </div>
                            </div>
                        </div>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</section>