config/routes.rb
Rails.application.routes.draw do

  post "contact", to: "notifications#contact", as: :contact_us

  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create", as: :login_post
  get "logout", to: "sessions#destroy", as: :logout
  get "register", to: "users#new", as: :register_user

  post "user/reset", to: "password_resets#create", as: :password_reset
  get "user/reset", to: "password_resets#new", as: :new_password_reset
  get "user/activate/:token", to: "password_resets#edit", as: :edit_password_reset

  get "dashboard", to: "dashboards#index", as: :dashboard

  resource :users, path: "user"

  resources :events

  root "static_pages#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="//use.typekit.net/pkp8swn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
</head>

<%= content_tag(:body, id: body_id, class: body_class) do %>
    <div class="page">

        <header id="header" class="site-header">
            <h1 class="logo">
                <% if signed_in? %>
                    <%= link_to "Plannr", dashboard_url %>
                <% else %>
                    <%= link_to "Plannr", root_url %>
                <% end %>
            </h1>

            <nav>
                <% if signed_in? %>
                    <%= link_to "Welcome, #{current_user.first_name.capitalize}", edit_users_path %>
                    <%= link_to "Logout", logout_path %>
                <% else %>
                    <%= link_to "Login", login_path, class: "login", data: { toggle: "login-form" } %>
                    <div id="login-form" class="login-form toggle">
                        <%= render 'shared/login_form' %>
                    </div>
                <% end %>
            </nav>
        </header>

        <div id="main" class="site-main">
            <% flash.each do |type, msg| %>
                <div class="alert-box <%= type %>">
                    <p><%= msg %></p>
                </div>
            <% end %>

            <%= yield %>

        </div>

        <footer id="footer">
            <div class="site-footer">
                <div class="container">
                    <p>&copy; <%= Time.now.year %> Plannr. All rights reserved.</p>
                </div>
            </div>
        </footer>

    </div>

    <%= debug(params) if Rails.env.development? %>
<% end %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50603558-1', 'yourplannr.com');
  ga('send', 'pageview');

</script>
</html>